# Generated by Django 3.0.4 on 2020-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200803_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='year_started',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
