# Generated by Django 3.0.4 on 2020-08-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200803_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='JobHistory',
        ),
    ]
