# Generated by Django 3.0.4 on 2020-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200803_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='organisation',
            field=models.CharField(max_length=200),
        ),
    ]
