from django.urls import path

from base.views import (
    base,
    home,
    allnews,
    allevents,
    allstory,
    allGallery,
    speceficevent,
    speceficnews,
    profile,
    searchalumni,
    speceficstory,
    autocomplete,
    jobsection,
    verification_alumni,
    addnews,
    addstory,
    addevent,
    send_p2pnotifs,
    notifications,
    notif_read,
    eventregistration,
    eventregistrationlist,
    dashboard,
    analytics,
    recommend,
    analytics_dataset,
    facultylist,
    search_alumni_admin,
)

app_name = 'base'

urlpatterns = [
    path('', home, name="home"),
    path('profile/<slug:user_name>/<int:user_id>', profile, name="profile"),
    path('event/<int:event_id>', speceficevent, name="speceficevent"),
    path('news/<int:news_id>', speceficnews, name="speceficnews"),
    path('story/<int:story_id>', speceficstory, name="speceficstory"),
    path('news', allnews, name="allnews"),
    path('events', allevents, name="allevents"),
    path('stories', allstory, name="allstory"),
    path('gallery', allGallery, name="allGallery"),
    path('searchalumni', searchalumni, name="searchalumni"),
    path('autocomplete', autocomplete, name="autocomplete"),
    path('jobsection', jobsection, name="jobsection"),
    path('verifialumni', verification_alumni, name="verification_alumni"),
    path('addstory', addstory, name="addstory"),
    path('addevent', addevent, name="addevent"),
    path('addnews', addnews, name="addnews"),
    path('sendnotifs/', send_p2pnotifs, name="sendnotifs"),
    path('notifications/', notifications, name="notifications"),
    path('notifsread/', notif_read, name="readnotifs"),
    path('eventregistrationlist/<int:event_id>', eventregistrationlist, name="eventregistrationlist"),
    path('eventregistration/<int:event_id>', eventregistration, name="eventregistration"),
    path('dashboard', dashboard, name="dashboard"),
    path('analytics', analytics, name="analytics"),
    path('analytics_dataset/', analytics_dataset, name="analytics_dataset"),
    path('recommend', recommend, name="recommend"),
    path('facultylist', facultylist, name="facultylist"),
    path('searchalumniadmin', search_alumni_admin, name="search_alumni_admin")
]
